name: E2E Tests Post Deploy

on:
  workflow_run:
    workflows: ['Deployment Orchestrator']
    types:
      - completed
    branches:
      - main

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Run E2E Tests Post Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Setup Docker
        run: |
          docker --version
          docker-compose --version
      - name: Run E2E tests in Docker
        run: npm run test:e2e:docker
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-post-deploy
          path: playwright-report/
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-post-deploy
          path: test-results/
